apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-dep
  namespace: backend  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: dtharundev/thecicd:7458957
        ports:
        - containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: backend  
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port:  30002
      targetPort: 4000
  type: NodePort
