apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-dep
  namespace: backend  # ✅ Add this line
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: dtharundev/thecicd:latest
        ports:
        - containerPort: 3010
        env:
        - name: DB_URL
          valueFrom:
            secretKeyRef:
              name: backend-sec
              key: DB_URL
        - name: SEC
          valueFrom:
            secretKeyRef:
              name: backend-sec
              key: SEC
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: backend  # ✅ Add this line
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 3010
      targetPort: 3010
  type: ClusterIP
