apiVersion: v1
kind: Service
metadata:
  name: carpulze-service
  labels:
    app: carpulze
spec:
  type: LoadBalancer
  selector:
    app: carpulze
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000