apiVersion: apps/v1
kind: Deployment
metadata:
  name: carpulze-deployment
  labels:
    app: carpulze
spec:
  replicas: 3
  selector:
    matchLabels:
      app: carpulze
  template:
    metadata:
      labels:
        app: carpulze
    spec:
      containers:
      - name: carpulze
        image: dtharundev/carpulze
        ports:
        - containerPort: 3000

